name: Build and Deploy

on:
  - push
  - pull_request

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: ./ci_install.sh

    - name: "Build → armeabi-v7a"
      run: |
        . env.sh
        ./build.sh --all armeabi-v7a

    - name: "Build → arm64-v8a"
      run: |
        . env.sh
        ./build.sh --all arm64-v8a

    - name: "Build → x86"
      run: |
        . env.sh
        ./build.sh --all x86

    - name: "Build → x86_64"
      run: |
        . env.sh
        ./build.sh --all x86_64

    - name: Archive
      run: |
        shopt -s extglob
        cd deps && zip -9r ../deps-lite.zip -- */
        ls -lh ../deps-lite.zip

    - name: Upload and tag
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Build
        files: deps-lite.zip
        prerelease: false
        make_latest: true
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
